# Production Configuration
app:
  name: "RAG Chatbot"
  version: "2.0.0"
  debug: false

server:
  host: "${HOST:-0.0.0.0}"
  port: "${PORT:-8000}"

qdrant:
  url: "${QDRANT_URL}"
  api_key: "${QDRANT_API_KEY:-}"
  collection_name: "documents"
  vector_size: 768
  distance: "cosine"
  hybrid_search:
    dense_weight: 0.6
    sparse_weight: 0.4

embeddings:
  provider: "google"
  model: "models/text-embedding-004"
  sparse_model: "Qdrant/bm42-all-minilm-l6-v2-attentions"
  batch_size: 100

llm:
  providers: ["google", "anthropic", "openai"]
  default_provider: "openai"  # 기본 모델 설정 (google, anthropic, openai 중 선택)
  auto_fallback: true  # 자동 폴백 활성화
  fallback_order: ["openai", "anthropic", "google"]  # 폴백 순서 설정
  google:
    model: "gemini-2.0-flash-exp"
    api_key: "${GOOGLE_API_KEY:-}"
    temperature: 0.3
    max_tokens: 10000
  anthropic:
    model: "claude-sonnet-4-20250514"
    api_key: "${ANTHROPIC_API_KEY:-}"
    temperature: 0.3
    max_tokens: 10000
  openai:
    model: "gpt-5-2025-08-07"
    api_key: "${OPENAI_API_KEY:-}"
    temperature: 0.3
    max_tokens: 10000

document_processing:
  splitter_type: "recursive"
  chunk_size: 400
  chunk_overlap: 50
  max_file_size: 52428800  # 50MB

retrieval:
  max_sources: 25  # 검색 결과 수 증가 (20 -> 25)
  min_score: 0.15  # 유사도 임계값 15%로 설정
  top_k: 10       # 리랭킹 후 최종 10개 문서
  enable_reranking: true   # 리랭킹 활성화
  quality_threshold: 0.15  # 품질 검증 임계값 15%
  deduplication_enabled: true  # 중복 제거 활성화

reranking:
  enabled: true
  default_provider: "llm"  # API 키 없이 LLM 리랭킹 사용
  min_score: 0.15  # 리랭킹 후 최소 점수 15%
  providers:
    cohere:
      api_key: ""  # 필요시 API 키 추가
      model: "rerank-multilingual-v2.0"
    jina:
      api_key: ""  # 필요시 API 키 추가
      model: "jina-reranker-v1-base-en"
      endpoint: "https://api.jina.ai/v1/rerank"
    llm:
      enabled: true  # LLM 기반 리랭킹 활성화
      provider: "openai"  # OpenAI GPT-5-nano 사용
      model: "gpt-5-nano"  # 고속 분류/순위 작업 최적화
      max_tokens: 800

session:
  ttl: 7200  # 2시간으로 연장 (기존 1시간 → 2시간)
  max_exchanges: 10  # 최대 교환 수도 증가 (5 → 10)

logging:
  level: "DEBUG"
  format: "structured"

uploads:
  directory: "./uploads"
  max_file_size: 52428800
  allowed_types: [".pdf", ".txt", ".md", ".docx", ".xlsx", ".json"]