# Production Configuration
app:
  name: "RAG Chatbot"
  version: "2.0.0"
  debug: false

server:
  host: "${HOST:-0.0.0.0}"
  port: "${PORT:-8000}"

qdrant:
  url: "${QDRANT_URL}"
  api_key: "${QDRANT_API_KEY:-}"
  collection_name: "documents"
  vector_size: 768
  distance: "cosine"
  hybrid_search:
    dense_weight: 0.6
    sparse_weight: 0.4

embeddings:
  provider: "google"
  model: "models/text-embedding-004"
  sparse_model: "Qdrant/bm42-all-minilm-l6-v2-attentions"
  batch_size: 100

llm:
  providers: ["google", "anthropic", "openai"]
  google:
    model: "gemini-2.0-flash-exp"
    api_key: "${GOOGLE_API_KEY:-}"
    temperature: 0.3
    max_tokens: 2048
  anthropic:
    model: "claude-3-5-sonnet-20241022"
    api_key: "${ANTHROPIC_API_KEY:-}"
    temperature: 0.3
    max_tokens: 2048
  openai:
    model: "gpt-4o-mini"
    api_key: "${OPENAI_API_KEY:-}"
    temperature: 0.3
    max_tokens: 2048

document_processing:
  splitter_type: "recursive"
  chunk_size: 400
  chunk_overlap: 50
  max_file_size: 52428800  # 50MB

retrieval:
  max_sources: 25  # 검색 결과 수 증가 (20 -> 25)
  min_score: 0.4   # 유사도 임계값 완화 (0.5 -> 0.4)
  top_k: 15
  enable_reranking: true   # 리랭킹 활성화 시도
  quality_threshold: 0.3   # 품질 검증 임계값 추가
  deduplication_enabled: true  # 중복 제거 활성화

reranking:
  enabled: true
  default_provider: "llm"  # API 키 없이 LLM 리랭킹 사용
  min_score: 0.3  # 리랭킹 후 최소 점수
  providers:
    cohere:
      api_key: ""  # 필요시 API 키 추가
      model: "rerank-multilingual-v2.0"
    jina:
      api_key: ""  # 필요시 API 키 추가
      model: "jina-reranker-v1-base-en"
      endpoint: "https://api.jina.ai/v1/rerank"
    llm:
      enabled: true  # LLM 기반 리랭킹 활성화
      provider: "google"  # Google Gemini 사용
      max_tokens: 1000

session:
  ttl: 3600
  max_exchanges: 5

logging:
  level: "DEBUG"
  format: "structured"

uploads:
  directory: "./uploads"
  max_file_size: 52428800
  allowed_types: [".pdf", ".txt", ".md", ".docx", ".xlsx"]